### ISSUE TITLE
Webpack error for version 3.11 and 4.41

### ISSUE THREAD

**Issue by theomoji** [learn-co-curriculum/react-static-components-lab#7]
// ♥ npm start

> react-static-components-lab@0.1.0 start /Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000
> react-scripts start

/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/react-dev-utils/WebpackDevServerUtils.js:167
  compiler.hooks.done.tap('done', async stats => {
                                  ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/react-scripts/scripts/start.js:45:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-static-components-lab@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-static-components-lab@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kenwang90/.npm/_logs/2019-10-13T20_32_06_045Z-debug.log
[16:32:06] (master) react-static-components-lab-online-web-sp-000
// ♥ learn
/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/src/CatComponent.js: Only one default export allowed per module. (12:0)
  10 |   }
  11 | }
> 12 | export default CatComponent
     | ^
    at Parser.pp$5.raise (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.raiseDuplicateExportError (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:2819:8)
    at Parser.pp$1.checkDuplicateExports (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:2813:10)
    at Parser.pp$1.checkExport (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:2712:12)
    at Parser.pp$1.parseExport (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:2649:10)
    at Parser.parseExport (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:6000:20)
    at Parser.pp$1.parseStatement (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:1884:74)
    at Parser.parseStatement (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:1673:17)
    at parse (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-core/lib/transformation/file/index.js:485:15)
    at File.parseCode (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-core/lib/transformation/file/index.js:570:20)
    at /Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-core/lib/transformation/file/index.js:532:16)
    at Pipeline.transform (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.transformFileSync (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-register/lib/node.js:118:20)
    at loader (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/src/App.js:2:2)
    at Module._compile (module.js:570:32)
    at loader (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/test/index-test.js:4:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/kenwang90/Flatiron/Mod4_React/react-static-components-lab-online-web-sp-000/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by theomoji** [comment]
FIXED! 
Update Node to newest version. 
'npm install node'
